services:
  - type: web
    name: e2ee-messenger
    env: python
    region: virginia
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    # IMPORTANT: Python version must be here, not inside envVars
    pythonVersion: 3.12.0

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: e2ee-db
          property: connectionString
    autoDeploy: true

databases:
  - name: e2ee-db
    databaseName: e2ee_messenger
    user: e2ee_messenger_user
    plan: free
    region: virginia